---
- name: Install all required dependencies
  apt:
    name: "{{ item }}"
    state: installed
    force: yes
  with_items:
    - python
    - python-setuptools
    - python-dev
    - build-essential
    - python-pip
    - python-mysqldb 