apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    env: PROD
    app: nginx
    tier: front-end
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        env: PROD
        tier: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      tier: front-end